%YAML:1.0
---
version: "0.5.5"
driver_version: "0.5.5"
windowTitle: ""
langCode: en
cameraAddr: "0"
cameraApiPreference: 0
trackerNum: 1
markerSize: 5.0000000000000003e-02
numOfPrevValues: 1
quadDecimate: 1.
searchWindow: 2.5000000000000000e-01
usePredictive: 1
calibrationTracker: 0
chessboardCalib: 0
ignoreTracker0: 0
rotateCl: 0
rotateCounterCl: 0
coloredMarkers: 1
calibOffsetX: 0.
calibOffsetY: 100.
calibOffsetZ: 100.
calibOffsetA: 100.
calibOffsetB: 0.
calibOffsetC: 0.
circularWindow: 1
smoothingFactor: 5.0000000000000000e-01
camFps: 30
camHeight: 0
camWidth: 0
cameraSettings: 0
camLatency: 0.
circularMarkers: 0
trackerCalibDistance: 5.0000000000000000e-01
cameraCalibSamples: 15
settingsParameters: 0
cameraAutoexposure: 0.
cameraExposure: 0.
cameraGain: 0.
trackerCalibCenters: 0
depthSmoothing: 0.
additionalSmoothing: 0.
markerLibrary: 0
markersPerTracker: 45
calibScale: 1.
disableOpenVrApi: 0
