name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BINARY_DIR: build

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout project and recurse submodules.
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: If on Linux, Install GTK3 dev build.
        if: ${{ matrix.os == 'ubuntu-latest'}}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgtk-3-dev

      - name: Combine commit hash of submodules in deps.
        id: deps-hash
        shell: bash
        run: |
          echo "::set-output name=all::$(for d in deps/*/.git;do echo -n -$(git -C ${d%/.git} rev-parse --short HEAD);done)"

      - name: Check dep cache for matching OS and combined hash
        id: deps-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.BINARY_DIR }}/deps/install
          key: deps-${{ runner.os }}${{ steps.deps-hash.outputs.all }}

      - name: CMake configure, skip building deps if cached.
        run: >-
          cmake -B ${{ env.BINARY_DIR }}
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DCMAKE_INSTALL_PREFIX=install
          -DEXPORT_COMPILE_COMMANDS=0
          -DSKIP_BUILD_DEPS=${{ steps.deps-cache.outputs.cache-hit }}

      - name: CMake build release.
        run: cmake --build ${{ env.BINARY_DIR }} --config ${{ env.BUILD_TYPE }}
